#!/usr/bin/env python3

import argparse
from pyanimenc import Encode

parser = argparse.ArgumentParser(description='Encode audio.')
parser.add_argument('source', help='Audio source')
parser.add_argument('-q', default=4, type=int, choices=range(1, 6),
                    dest='q', help='Quality mode')
parser.add_argument('-c', default='m4a', choices=['aac', 'm4a'],
                    dest='c', help='Container')
args = parser.parse_args()

Encode(args.source).audio(q=args.q, c=args.c)

# vim: ts=4 sw=4 et:
