#!/usr/bin/env python3

import argparse
from pyanimenc import Encode

parser = argparse.ArgumentParser(description='Encode audio.')
parser.add_argument('source', help='Video source')
parser.add_argument('-q', default=15, type=int, choices=range(1, 52),
                    dest='q', help='Quality mode')
parser.add_argument('-d', default=10, choices=[8, 10],
                    dest='d', help='Bit depth')
parser.add_argument('-p', default='slow',
                    choices=['ultrafast', 'superfast', 'veryfast', 'faster',
                             'fast', 'medium', 'slow', 'slower', 'veryslow',
                             'placebo'], dest='p', help='Preset')
parser.add_argument('-t', default='animation',
                    choices=['film', 'animation', 'grain', 'stillimage',
                             'psnr', 'ssim', 'fastdecode', 'zerolatency'],
                    dest='t', help='Tune')
args = parser.parse_args()

Encode(args.source).video(q=args.q, d=args.d, p=args.p, t=args.t)

# vim: ts=4 sw=4 et:
